.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright (C) 2024 Matteo Cavestri
.TH PWD 1 "November 2024" "Userland Utilities" "User Commands"
.SH NAME
pwd \- print working directory
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
Print the absolute pathname of the current working directory to standard output.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B >0
Error occurred.
.SH STANDARDS
POSIX.1-2017
.SH SEE ALSO
.BR cd (1),
.BR ls (1)
.SH AUTHOR
Matteo Cavestri
