.\" SPDX-License-Identifier: GPL-3.0-or-later
.\" Copyright (C) 2024 Matteo Cavestri
.TH TRUE 1 "November 2024" "Userland Utilities" "User Commands"
.SH NAME
true \- return successful exit status
.SH SYNOPSIS
.B true
.SH DESCRIPTION
Exit with status code 0. All arguments are ignored.
.SH EXIT STATUS
Always returns 0.
.SH STANDARDS
POSIX.1-2017
.SH SEE ALSO
.BR false (1)
.SH AUTHOR
Matteo Cavestri
